# pipenv run esphome run serra_scale.yaml
# pipenv run esphome logs serra_scale.yaml

esphome:
  name: scale


esp32:
  board: esp32dev
  framework:
    type: arduino


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
# TODO: in produzione level: WARN
logger:
  # level: WARN

mqtt:
  broker: !secret mqtt_broker
  port: 1883


# Example configuration entry
sensor:
  - platform: ultrasonic
    trigger_pin: 23
    echo_pin: 22
    name: "Ultrasonic Sensor"
    update_interval: 5s